databases:
  - name: metabase
    region: frankfurt
    plan: starter
    databaseName: metabase

services:
  - type: web
    name: metabase
    env: docker
    repo: https://github.com/render-examples/metabase
    region: frankfurt
    plan: starter
    branch: master
    healthCheckPath: /api/health
    envVars:
      - key: MB_DB_CONNECTION_URI
        fromDatabase:
          name: metabase
          property: connectionString


